// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: metrics.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Metrics_PostNewMetrics_FullMethodName                  = "/proto.Metrics/PostNewMetrics"
	Metrics_GetLatestMetrics_FullMethodName                = "/proto.Metrics/GetLatestMetrics"
	Metrics_PostNewExternalApplicationsList_FullMethodName = "/proto.Metrics/PostNewExternalApplicationsList"
)

// MetricsClient is the client API for Metrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsClient interface {
	PostNewMetrics(ctx context.Context, in *NewMetricsArray, opts ...grpc.CallOption) (*PostNewMetricsResp, error)
	GetLatestMetrics(ctx context.Context, in *GetLatestMetricsReq, opts ...grpc.CallOption) (*GetLatestMetricsResp, error)
	PostNewExternalApplicationsList(ctx context.Context, in *ExternalApplicationsList, opts ...grpc.CallOption) (*ExternalApplicationsList, error)
}

type metricsClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsClient(cc grpc.ClientConnInterface) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) PostNewMetrics(ctx context.Context, in *NewMetricsArray, opts ...grpc.CallOption) (*PostNewMetricsResp, error) {
	out := new(PostNewMetricsResp)
	err := c.cc.Invoke(ctx, Metrics_PostNewMetrics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) GetLatestMetrics(ctx context.Context, in *GetLatestMetricsReq, opts ...grpc.CallOption) (*GetLatestMetricsResp, error) {
	out := new(GetLatestMetricsResp)
	err := c.cc.Invoke(ctx, Metrics_GetLatestMetrics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) PostNewExternalApplicationsList(ctx context.Context, in *ExternalApplicationsList, opts ...grpc.CallOption) (*ExternalApplicationsList, error) {
	out := new(ExternalApplicationsList)
	err := c.cc.Invoke(ctx, Metrics_PostNewExternalApplicationsList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServer is the server API for Metrics service.
// All implementations must embed UnimplementedMetricsServer
// for forward compatibility
type MetricsServer interface {
	PostNewMetrics(context.Context, *NewMetricsArray) (*PostNewMetricsResp, error)
	GetLatestMetrics(context.Context, *GetLatestMetricsReq) (*GetLatestMetricsResp, error)
	PostNewExternalApplicationsList(context.Context, *ExternalApplicationsList) (*ExternalApplicationsList, error)
	mustEmbedUnimplementedMetricsServer()
}

// UnimplementedMetricsServer must be embedded to have forward compatible implementations.
type UnimplementedMetricsServer struct {
}

func (UnimplementedMetricsServer) PostNewMetrics(context.Context, *NewMetricsArray) (*PostNewMetricsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostNewMetrics not implemented")
}
func (UnimplementedMetricsServer) GetLatestMetrics(context.Context, *GetLatestMetricsReq) (*GetLatestMetricsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestMetrics not implemented")
}
func (UnimplementedMetricsServer) PostNewExternalApplicationsList(context.Context, *ExternalApplicationsList) (*ExternalApplicationsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostNewExternalApplicationsList not implemented")
}
func (UnimplementedMetricsServer) mustEmbedUnimplementedMetricsServer() {}

// UnsafeMetricsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServer will
// result in compilation errors.
type UnsafeMetricsServer interface {
	mustEmbedUnimplementedMetricsServer()
}

func RegisterMetricsServer(s grpc.ServiceRegistrar, srv MetricsServer) {
	s.RegisterService(&Metrics_ServiceDesc, srv)
}

func _Metrics_PostNewMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMetricsArray)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).PostNewMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_PostNewMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).PostNewMetrics(ctx, req.(*NewMetricsArray))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_GetLatestMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestMetricsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).GetLatestMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_GetLatestMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).GetLatestMetrics(ctx, req.(*GetLatestMetricsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_PostNewExternalApplicationsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalApplicationsList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).PostNewExternalApplicationsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_PostNewExternalApplicationsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).PostNewExternalApplicationsList(ctx, req.(*ExternalApplicationsList))
	}
	return interceptor(ctx, in, info, handler)
}

// Metrics_ServiceDesc is the grpc.ServiceDesc for Metrics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metrics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostNewMetrics",
			Handler:    _Metrics_PostNewMetrics_Handler,
		},
		{
			MethodName: "GetLatestMetrics",
			Handler:    _Metrics_GetLatestMetrics_Handler,
		},
		{
			MethodName: "PostNewExternalApplicationsList",
			Handler:    _Metrics_PostNewExternalApplicationsList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metrics.proto",
}
